
server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.101/immstest?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tyq030420!
