server:
  port: 8081
  address: 0.0.0.0
jasypt:
  encryptor:
    password: 123456

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://111.229.32.218:3306/imms_test?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: imms_test
    password: ENC(MuSR2uJS1WGtzev7H8pch1JYsc+bVsdBGixsxnQwiChEoq4NA+Pp7F26aeXTzZ4C)
  # Redis相关配置
  redis:
    host: 111.229.32.218
    port: 6379
    username: default
    password: ENC(q8aQHOWWOalQDQKzvY26L2cZ8SA3EqVUXHnJFhBoVDqp6m2ltye3iG6h9s3OW2rd)
    # 第0号数据库
    database: 0
    jedis:
      #Redis连接池配置
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0
  # 邮件服务配置
  mail:
    host: smtp.163.com # 网站发送邮件邮箱服务 host
    port: 465
    username: a1137109222@163.com # 邮箱
    password: ENC(ZBAdlOpfQuAw0xOydfBuDuXx9cEdjXmLQr2pHDmK8qMhw+9rKnLLDmlbH6Ss9aKwexcce1VJENgP+L1Bv3wBmA==)
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory