server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/imms?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: imms
    password: 123456